//
//  Constants.swift
//  com.tbox.fotki
//
//  Created by Dilawer Hussain on 12/27/16.
//  Copyright © 2020 Fotki. All rights reserved.
//

import Foundation

//MARK: -Api Base URL
let kbaseURL = "https://api.fotki.com/v3"

/*//Album XML Tag
 #define kprivate        @"private"
 #define kpublic         @"public"
 #define kaccount_tree         @"account_tree"
 #define kfolder_name         @"folder_name"
 #define kdesc         @"desc"
 #define kdescr         @"descr"
 #define kfolder_id_enc         @"folder_id_enc"
 #define kalbum_id_enc         @"album_id_enc"
 #define kcurrent_page         @"current_page"
 #define kphotos         @"photos"
 #define kisVideo         @"video"
 #define kfaved_by_owner         @"faved_by_owner"
 #define kId         @"id"
 #define kthumbnail_url      @"thumbnail_url"
 #define koriginal_url       @"original_url"
 #define kview_url       @"view_url"
 #define khas_original       @"has_original"
 #define kdescription       @"description"
 #define kalbum_date       @"album_date"
 #define kvideo_url       @"video_url"
 #define kerror       @"error"
 
 
 #define kAlbumResultTag @"result"
 #define kAlbumFoldersTag @"folders"
 #define kAlbumFolderTag @"folder"
 #define kAlbumFolderCreatedTag @"created"
 #define kAlbumFolderIDTag @"folder_id"
 #define kAlbumFolderDescriptionTag @"desc"
 #define kAlbumFolderName @"folder_name"
 #define kAlbumFolderURL @"url_p"
 #define kAlbumAlbumsTag @"albums"
 #define kAlbumAbumTag @"album"
 #define kAlbumAbumDescriptionTag @"desc"
 #define kAlbumNameTag @"name"
 #define kAlbumCreatedTag @"created"
 #define kAlbumIDTag @"id"
 #define kAlbumSizeTag @"size"
 #define kAlbumURLTag @"url_p"
 
 // Upload XML Tag
 #define kUploadResultTag @"result"
 #define kUploadAlreadyExistTag @"already_exists"
 #define kUploadPhotoIDTag @"photo_id"
 #define kUploadSpaceLimitTag @"space_limit"
 #define kUploadSpaceUsedTag @"space_used"
 #define kUploadVIHeightTag @"vi_height"
 #define kUploadVIWidthTag @"vi_width"
 #define kUploadViewURLTag @"view_url"
 
 */

// API METHODS

let knew_session = "/new_session?"
let kget_account_info = "/get_account_info?"
let kget_account_tree = "/get_account_tree?"
let kget_album_items_count = "/get_album_items_count?"
let kget_album_content = "/get_album_content?"
let kget_folder_content = "/get_folder_content?"
let kcreate_album = "/create_album?"
let kcreate_folder = "/create_folder?"
let kupdate_album = "/update_album?"
let kupdate_folder = "/update_folder?"
let kupload = "/upload"
let kgoogle_new_session = "/google_new_session?"
let kfacebook_new_session = "/facebook_new_session?"



// KeyValue of parameters/responses
let klogin = "login"
let kavatar_url = "avatar_url"
let kgmailLogin = "gmailLogin"
let kfacebookLogin = "facebookLogin"
let kpassword = "password"
let kaccess_token = "access_token"
let kos = "os"
let kok = "ok"
let kdata = "data"
let klogins = "logins"
let kresult = "result"
let kmessage = "message"
let kid = "id"
let ktitle = "title"
let kaccount_info = "account_info"
let kspace_limit = "space_limit"
let kuser_id = "user_id"
let kdisp_name = "disp_name"
let kname = "name"
let kdate = "date"
let kdescription = "description"
let kdescr = "descr"
let kenc_user_id = "enc_user_id"
let kaccount_type = "account_type"
let kavatar = "avatar"
let kspace_used = "space_used"
let kmember_since = "member_since"
let kurl = "url"
let kheight = "height"
let kcustom = "custom"
let kaccounts_found = "accounts_found"
let kwidth = "width"
let kftp_enabled = "ftp_enabled"
let kexternal_linking_allowed = "external_linking_allowed"
//let klogin:String = "login"
let kservice_storage_originals_is_enabled = "service_storage_originals_is_enabled"
let kis_video_enabled = "is_video_enabled"
let kalbum_id = "album_id"
let kfolder_id = "folder_id"
let kitems_count = "items_count"
let kaccount_tree = "account_tree"
let knumber_of_albums = "number_of_albums"
let knumber_of_folders = "number_of_folders"

//KeyValues used in App
let KUPDATE_ALBUM = "kupdate_album"
let KUPDATE_FOLDER = "kupdate_folder"
let kpublic = "public"
let kprivate = "private"
let kprofile = "profile"
let kuploadIcon = "uploadIcon"
let kLogoutMessage = "Are you sure you want to logout"
let kFile_has_been_shared = "File has been shared"
let kFile_has_been_mailed = "File has been mailed"
let kFile_has_been_sent = "File has been sent"
let kFile_has_been_assigned_to_contact = "File has been assigned to contact"
let kFile_has_been_printed = "File has been printed"
let kFile_has_been_added_to_reading_list = "File has been added to reading list"
let kFile_has_been_added_to_notes = "File has been added to notes"
let kFile_has_been_saved = "File has been saved"
let kFile_has_been_copied = "File has been copied"
let kSorry_Error_sharing_file = "Sorry. Error sharing file"
let kError_loading_video_please_contact_Fotki_customer_service = "Error loading video, please contact Fotki customer service."
let kUploading_is_in_progress = "Uploading is in progress"
let kActivityTypeNotes = "com.apple.mobilenotes.SharingExtension"
let kYes = "Yes"
let kNo = "No"
let kalbums = "albums"
let kalbum = "album"
let ksize = "size"
let kalbum_name = "album_name"
let kalbum_description = "album_description"
let kfolders = "folders"
let kphotos = "photos"
let kthumbnail_url = "thumbnail_url"
let koriginal_url = "original_url"
let kcollection_cell = "collection_cell"
let kcollection_cell_iphone = "collection_cell_iphone"
let kview_url = "view_url"
let kcreated = "created"
let kUploading = "Uploading"
let kLoginViewController = "LoginViewController"
let kCollectionViewCell = "CollectionViewCell"
let kCollectionViewIphoneCell = "CollectionViewIphoneCell"
let kFolderViewController = "FolderViewController"
let kFoldersViewController = "FoldersViewController"
let kAlbumViewController = "AlbumViewController"
let kVideoViewController = "VideoViewController"
let kActionsViewController = "ActionsViewController"
let kShowUsersViewController = "ShowUsersViewController"
let kDownloadFileViewController = "DownloadFileViewController"
let kUploadViewController = "UploadViewController"
let kProfileViewController = "ProfileViewController"
let kvideo = "video"
let kNSCFNumber = "__NSCFNumber"
let kfolderImage = "folder-icon.png"
let kalbumImage = "album-icon.png"
let kmenuImage = "menu"
let klogoImage = "logo.png"
let kPlayImage = "play.png"
let kplaceHolder = "placeholder.png"
let kMenuViewController = "MenuViewController"
let kError = "Error"
let kOK = "OK"
let kReturn = "Return"
let kof = "of"
let kTableViewCell = "TableViewCell"
let kcell = "cell"
let kuserCell = "userCell"
let kUserTableViewCell = "UserTableViewCell"
let kcover_photo_url = "cover_photo_url"
let kfolder_name = "folder_name"
let kdesc = "desc"
let kalbum_id_enc = "album_id_enc"
let knumber_of_videos = "number_of_videos"
let knumber_of_photos = "number_of_photos"
let koriginal_img_height = "original_img_height"
let koriginal_img_width = "original_img_width"
let kview_img_height = "view_img_height"
let kview_img_width = "view_img_width"
let kfile_sizes = "file_sizes"
let khas_original = "has_original"
let kor_size = "or_size"
let kvi_size = "vi_size"
let kth_size = "th_size"
let kimage_size = "image_size"
let kfolder_id_enc = "folder_id_enc"
let kCreate_Folder = "Create Folder"
let kCreate_Album = "Create Album"
let kPublic_Home = "Public Home"
let kPrivate_Home = "Private Home"
let kUpdate_Folder = "Folder Properties"
let kAlbum_Properties = "Album Properties"
let kUpload_Files = "Upload Files"
let kCopyToClipboard = "Copy To Clipboard"
let kRefresh = "Refresh"
let kShareAlbumLink = "Share Album Link"
let kShareFolderLink = "Share Folder Link"
let kActions = "Actions"
let kAction = "Action"
let kCreate = "Create"
let kShare = "Share"
let kSave = "Save"
let kCancel = "Cancel"
let kdot = "dot"
let kFolder_Name = "Folder Name"
let kAlbum_Name = "Album Name"
let kme = "me"
let kfields = "fields"
let kfirst_name = "first_name"
let klast_name = "last_name"
let kemail = "email"
let klarge = "large"
let ktype = "type"
let kpicture = "picture"
let kURL = "URL"
let kZeroPercent = "0%"
let kphoto = "photo"
let kimagePng = "image/png"
let kgif = ".gif"
let kUploadProgress = "Upload Progress"
let kGmailLogout = "Gmail Logout"
let kFacebookLogout = "Facebook Logout"
let kGoogleLogin = "Google Login"
let kReloadData = "ReloadData"
let kSessionExpired = "SessionExpired"
let kJSON = "JSON"
let kVideoMp4 = "video/mp4"
let kTempMp4 = "temp.mp4"
let kTempPng = "temp.png"
let kuploadedCount = "uploadedCount"
let ktotalCount = "totalCount"
let kcompletion = "completion"
let krecallApi = "recallApi"
let kcurrent_page = "current_page"
let kyes = "Yes"
let kno = "No"
let kResized = "Resized"
let kUpload = "Upload"
let kPrivate = "Private"
let kPublic = "Public"
let kOriginals = "Originals"
let kOriginal = "Original"
let kattributedMessage = "attributedMessage"
let kRotateParent   = "RotateParent"

//alert messages and long strings

let kThe_username_or_password_is_not_correct_Try_again = "The username or password is not correct. Try again."
let kNo_accounts_found_against_this_email = "No accounts found against this email"
let kUsername_or_Password_is_missing = "Username or Password is missing"
let kAre_you_sure_you_want_to_logout = "Are you sure you want to logout?"
let kThe_folder_name_is_missing = "The folder name is missing"
let kThe_folder_description_is_missing = "The folder description is missing"
let kThe_album_name_is_missing = "The album name is missing"
let kThe_album_description_is_missing = "The album description is missing"
let kInternet_Issue = "Internet Issue"
let kLinkCopiedToClipboard = "Link copied to clipboard"
let kCannot_connect_right_now_Please_check_internet_connection = "Cannot connect right now. Please check internet connection"
let kAlbum_is_empty_do_you_want_to_upload_photos_and_videos = "Album is empty, Do you want to upload photos and videos?"
let kYour_account_has_been_temporary_suspended_due_to_membership_expiration = "Your account has been temporary suspended due to membership expiration. Please visit Fotki using internet browser to renew your subscription."
let kThe_Internet_connection_appears_to_be_offline = "The Internet connection appears to be offline."
let kSomething_went_wrong_with_this_album = "Something went wrong with this album"
let kEmpty_Album = "Empty Album"
let kWrong_session_id = "Wrong session_id"
let kFolder_has_been_created = "Folder has been created"
let kAlbum_has_been_created = "Album has been created"
let kFolder_info_has_been_updated = "Folder info has been updated"
let kAlbum_info_has_been_updated = "Album info has been updated"
let kImage_is_not_in_acceptable_format = "Image is not in acceptable format"
let kfiles_have_been_uploaded  = "files have been uploaded"
let kUpload_is_done = "Upload is done!"
let kResize_photos_before_uploading = "Resize photos before uploading?"
let kPlease_select_album_to_upload = "Please open an album to upload."
let kNo_File_is_currently_uploading = "No file is currently uploading"
let kShare_Media = "Share Media"
let kImage_resize_option_text = "Would you like to upload Resized versions of your photos or upload Originals? Please keep in mind that uploading Originals may take more time"
let kShare_image_resize_option_text = "Would you like to share Resized versions of your photos or share Originals? Please keep in mind that sharing Originals may take more time"
